### DISCUSSION TITLE
Setting up an automation on device connection

### DISCUSSION THREAD

**Discussion by go-ob** [travisghansen/hass-pfsense#75] [Q&A]
Hi all,

I have successfully set up the integration and enabled the device tracker on my iphone and I have the entity device_tracker.gnr_iphone on my list.

What would be the right way of creating an automation that is triggered by my iphone connecting to my pfsense network?

Thank you in advance,

**Comment by travisghansen** [comment]
Does something like this not work?

```
trigger:
  platform: zone
  event: enter
  zone: zone.home
  entity_id: device_tracker.<id>
```

- https://community.home-assistant.io/t/device-tracker-automation/17609
